const gameTitles = [
"warpips",
"recipe for disaster",
"dishonored®: death of the outsider™",
"city of gangsters",
"hell is others",
"adios",
"epistory - typing chronicles",
"heroes & generals wwii",
"fall guys",
"gamedec - definitive edition",
"first class trouble",
"kerbal space program",
"shadow tactics - aiko's choice",
"eximius: seize the frontline",
"dishonored - definitive edition",
"mortal shell",
"severed steel",
"f.i.s.t.: forged in shadow torch",
"encased",
"fallout: a post nuclear role playing game",
"fallout tactics: brotherhood of steel",
"fallout 2: a post nuclear role playing game",
"lego® builder's journey",
"them's fightin' herds",
"sable",
"bloons td 6",
"wildcat gun machine",
"saints row iv re-elected",
"rpg in a box",
"fort triumph",
"star wars™: squadrons",
"dark deity",
"evil dead: the game",
"epic cheerleader pack",
"shadow tactics: blades of the shogun",
"alba - a wildlife adventure",
"filament",
"warhammer 40,000: mechanicus - standard editio...",
"saturnalia",
"fallout 3: game of the year edition",
"evoland legendary edition",
"toejam & earl: back in the groove!",
"darkwood",
"slain: back from hell",
"rising hell",
"the drone racing league®",
"runbow",
"gloomhaven",
"spirit of the north",
"realm royale reforged epic launch bundle",
"hundred days - winemaking simulator",
"knockout city™",
"submerged: hidden depths",
"destiny 2: bungie 30th anniversary pack",
"ring of pain",
"rumbleverse™ - boom boxer content pack",
"doom 64",
"cook, serve, delicious! 3?!",
"unrailed!",
"lawn mowing simulator",
"tannenberg",
"shop titans",
"wonder boy the dragons trap",
"ancient enemy",
"iratus: lord of the dead",
"hood: outlaws & legends",
"geneforge 1 - mutagen",
"car mechanic simulator 2018",
"a game of thrones: the board game digital edit...",
"supraland",
"maneater",
"wolfenstein: the new order",
"bioshock: the collection",
"borderlands 3",
"jotun: valhalla edition",
"redout: enhanced edition",
"terraforming mars",
"paradigm",
"just die already",
"riverbond",
"amnesia: rebirth",
"xcom® 2",
"insurmountable",
"rogue legacy",
"city of brass",
"demon's tilt",
"in sound mind",
"epic slayer kit",
"centipede: recharged",
"black widow: recharged",
"cris tales",
"brothers - a tale of two sons",
"windbound",
"yooka-laylee and the impossible lair",
"daemon x machina",
"relicta",
"gods will fall",
"tomb raider game of the year edition",
"shadow of the tomb raider: definitive edition",
"salt and sanctuary",
"moving out",
"mages of mystralia",
"prey",
"pathfinder: kingmaker - enhanced plus edition",
"vampyr",
"mutant year zero: road to eden",
"second extinction™",
"loop hero",
"the vanishing of ethan carter",
"shenmue iii - standard edition",
"prison architect",
"godfall challenger edition",
"while true: learn()",
"dead by daylight",
"antstream - epic welcome pack",
"antstream arcade",
"thehunter: call of the wild™",
"never alone (kisima ingitchuna)",
"kid a mnesia exhibition",
"guild of dungeoneering",
"rogue company season four epic pack",
"tiny tina's assault on dragon keep: a wonderla...",
"aven colony",
"darq: complete edition",
"among the sleep - enhanced edition",
"stubbs the zombie in rebel without a pulse",
"paladins epic pack",
"pc building simulator",
"europa universalis iv",
"the escapists",
"tharsis",
"speed brawl",
"nioh: the complete edition",
"sheltered",
"yoku's island express",
"automachef",
"saints row®: the third™  remastered",
"yooka-laylee",
"void bastards",
"rebel galaxy",
"minit",
"a plague tale: innocence",
"train sim world 2",
"mothergunship",
"verdun",
"offworld trading company",
"obduction",
"ironcast",
"bridge constructor the walking dead",
"the spectrum retreat",
"sonic mania",
"horizon chase turbo",
"overcooked! 2",
"hell is other demons",
"genshin impact",
"control",
"frostpunk",
"among us",
"nba 2k21",
"rogue company",
"scavengers",
"the lion's song",
"pine",
"idle champions of the forgotten realms",
"alien: isolation",
"hand of fate 2",
"spellbreak",
"the first tree",
"ken follett's the pillars of the earth",
"deponia: the complete journey",
"3 out of 10: season two",
"tales of the neon sea",
"magic: legends",
"creature in the well",
"the fall",
"surviving mars - mysteries resupply pack",
"surviving mars",
"wargame: red dragon",
"sunless sea",
"rage 2",
"absolute drift",
"halcyon 6",
"metro: last light redux",
"dandara: trials of fear edition",
"galactic civilizations iii",
"star wars™ battlefront™ ii: celebration editio...",
"crying suns",
"jurassic world evolution",
"stranded deep",
"night in the woods",
"my time at portia",
"darkest dungeon®: the musketeer",
"darkest dungeon®",
"inside",
"tropico 5",
"metro: 2033 redux",
"alien: isolation",
"defense grid: the awakening",
"the long dark",
"oddworld: new 'n' tasty",
"cities: skylines - match day",
"cities: skylines - carols, candles and candy",
"cities: skylines - pearls from the east",
"cities: skylines",
"tyranny - gold edition",
"pillars of eternity - definitive edition",
"crsed: f.o.a.d.",
"cave story+",
"mudrunner",
"the world next door",
"elite dangerous",
"the textorcist",
"dungeons 3",
"ghostbusters: the video game remastered",
"blair witch",
"layers of fear 2",
"costume quest 2",
"kingdom new lands",
"amnesia: a machine for pigs",
"rocket league®",
"rising storm 2: vietnam",
"abzu",
"free tough enough primary wrap",
"pikuniku",
"rollercoaster tycoon® 3: complete edition",
"watch dogs 2",
"football manager 2020",
"where the water tastes like wine",
"railway empire",
"diabotical",
"into the breach",
"hitman",
"shadowrun collection",
"enter the gungeon",
"god's trigger",
"remnant: from the ashes",
"a total war saga: troy",
"the alto collection",
"3 out of 10 ep 1 welcome to shovelworks",
"wilmot's warehouse",
"superbrothers: sword & sworcery ep",
"barony",
"20xx",
"tacoma",
"torchlight ii",
"killing floor 2",
"hue",
"aer memories of old",
"stranger things 3: the game",
"pathway",
"sludge life",
"ark: survival evolved",
"samurai shodown neogeo collection",
"overcooked",
"trackmania",
"borderlands: the handsome collection",
"sid meier's civilization vi",
"grand theft auto v",
"death coming",
"crashlands",
"amnesia: the dark descent",
"for the king",
"wheels of aurelia",
"just cause 4",
"sherlock holmes crimes and punishments",
"close to the sun",
"drawful 2",
"gone home",
"totally reliable delivery service",
"hob",
"the stanley parable",
"watch dogs standard edition",
"gonner",
"darksiders ii deathinitive edition",
"steep",
"darksiders warmastered edition",
];